// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQna5pkxaj8mgSkK9_NFItKasIpC3ll8',
    appId: '1:852102538939:web:891d7f1a8e1fd3149fab9e',
    messagingSenderId: '852102538939',
    projectId: 'sgroup-cc21d',
    authDomain: 'sgroup-cc21d.firebaseapp.com',
    storageBucket: 'sgroup-cc21d.firebasestorage.app',
    measurementId: 'G-2BNEBN0HP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcjAyMYz4xA47tVw3f_nFAVeb8mzwX6TI',
    appId: '1:852102538939:android:8aac844cbf219b539fab9e',
    messagingSenderId: '852102538939',
    projectId: 'sgroup-cc21d',
    storageBucket: 'sgroup-cc21d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nA0xrSTfxFiy2nlVP7p_ki4RsfUzP0w',
    appId: '1:852102538939:ios:4b56c7cf9582e5fb9fab9e',
    messagingSenderId: '852102538939',
    projectId: 'sgroup-cc21d',
    storageBucket: 'sgroup-cc21d.firebasestorage.app',
    iosClientId: '852102538939-b0bh3iuk543g57i0daho5tftf6j52a4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.sg',
  );
}
